repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            frontend/src/__tests__/.*\.tsx\.snap |
            frontend/.*\.min\..*
          )$
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-added-large-files
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            frontend/src/__tests__/.*\.tsx\.snap |
            frontend/.*\.min\..* |
            .*\.bin
          )$
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix']
        exclude: |
          (?x)^(
            .*/?package-lock.json |
            lambdas/jwks-key-rotation/src/__tests__/utils/test-public-key.jwks.json
          )$

  - repo: https://github.com/NHSDigital/nhs-notify-shared-modules
    rev: 3.0.8
    hooks:
      - id: sort-dictionary
      - id: scan-secrets
        args: [check=whole-history]
      - id: check-file-format
        args: [check=branch]
      - id: check-markdown-format
        args: [check=branch]
      - id: check-english-usage
        args: [check=branch]
      - id: lint-terraform
      - id: generate-terraform-docs
      - id: check-todo-usage
        args: [check=branch]
