#!/usr/bin/env bash

# WARNING: Please DO NOT edit this file! It is maintained in the Repository Template (https://github.com/NHSDigital/nhs-notify-repository-template). Raise a PR instead.

set -euo pipefail

# TFSec command wrapper. It will run the command natively if TFSec is
# installed, otherwise it will run it in a Docker container.
# Run tfsec for security checks on Terraform code.
#
# Usage:
#   $ ./trivy.sh [directory]
# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"

  local dir_to_scan=${1:-.}

  if command -v trivy > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    # shellcheck disable=SC2154
    run-trivy-natively "$dir_to_scan"
  else
    run-trivy-in-docker "$dir_to_scan"
  fi
}

# Run trivy on the specified directory.
# Arguments:
#   $1 - Directory to scan
function run-trivy-natively() {

  local dir_to_scan="$1"

  echo "Trivy found locally, running natively"

  echo "Running Trivy on directory: $dir_to_scan"
  trivy config \
    --config scripts/config/trivy.yaml \
    --tf-exclude-downloaded-modules \
    "${dir_to_scan}"

  check-trivy-status
}

# Check the exit status of tfsec.
function check-trivy-status() {

  if [ $? -eq 0 ]; then
    echo "Trivy completed successfully."
  else
    echo "Trivy found issues."
    exit 1
  fi
}

function run-trivy-in-docker() {

  # shellcheck disable=SC1091
  source ./scripts/docker/docker.lib.sh
  local dir_to_scan="$1"

  # shellcheck disable=SC2155
  local image=$(name=aquasec/trivy docker-get-image-version-and-pull)
  # shellcheck disable=SC2086
  echo "Trivy not found locally, running in Docker Container"
  echo "Running Trivy on directory: $dir_to_scan"
  docker run --rm --platform linux/amd64 \
    --volume "$PWD":/workdir \
    --workdir /workdir \
    "$image" \
    config \
    --config scripts/config/trivy.yaml \
    --tf-exclude-downloaded-modules \
    "${dir_to_scan}"
    check-trivy-status
}
# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
