# WARNING: Please DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

# The test types listed here are both those which might run both locally and in CI, or
# in one but not the other.  All of the test types listed at
# https://github.com/NHSDigital/software-engineering-quality-framework/blob/main/quality-checks.md
# should be represented here with the exception of:
#   - dependency scanning, which we expect to be applied at the repository level
#   - secret scanning, which we expect to be a pre-commit hook
#   - code review, which is outside the scope of automated testing for the moment

test-unit: # Run your unit tests from scripts/test/unit @Testing
	make _test name="unit"

test-lint: # Lint your code from scripts/test/lint @Testing
	make _test name="lint"

test-coverage: # Evaluate code coverage from scripts/test/coverage @Testing
	make _test name="coverage"

test-accessibility: # Run your accessibility tests from scripts/test/accessibility @Testing
	make _test name="accessibility"

test-ui: # Run your UI tests from scripts/test/ui @Testing
	make _test name="ui"

test-backend: # Run your backend tests from scripts/test/backend @Testing
	make _test name="backend"

test: # Run all the test tasks @Testing
	make \
		test-unit \
		test-lint \
		test-coverage \
		test-ui \
		test-backend \
		test-accessibility

_test:
	set -e
	script="./scripts/tests/${name}.sh"
	if [ -e "$${script}" ]; then
		exec $${script}
	else
		echo "make test-${name} not implemented: $${script} not found" >&2
	fi

${VERBOSE}.SILENT: \
	_test \
	test \
	test-accessibility \
	test-coverage \
	test-lint \
	test-ui \
	test-backend \
	test-unit \
