name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true
    default: main

  targetEnvironment:
    description: Name of the environment under test
    required: true
    default: main

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-iam-dev
    required: true

  targetComponent:
    description: Name of the component under test
    default: app

runs:
  using: "composite"

  steps:
    - name: Fetch terraform output
      uses: actions/download-artifact@v4
      with:
        name: terraform-output-${{ inputs.targetComponent }}
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci

    - name: Generate outputs file
      shell: bash
      run: |
        root_dir=${GITHUB_WORKSPACE}
        mv ./terraform_output.json ./sandbox_tf_outputs.json
        npm run generate-outputs sandbox-output

    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        make test-${{ inputs.testType }}

    - name: Archive ui test results
      if: ${{ inputs.testType == 'ui' }}
      uses: actions/upload-artifact@v4
      with:
        name: UI test report
        path: "tests/test-team/playwright-report-component-tests"

    - name: Archive backend test results
      if: ${{ inputs.testType == 'backend' }}
      uses: actions/upload-artifact@v4
      with:
        name: Backend test report
        path: "tests/test-team/playwright-report-backend-tests"

    - name: Archive accessibility results
      if: ${{ inputs.testType == 'accessibility' }}
      uses: actions/upload-artifact@v4
      with:
        name: accessibility
        path: ".reports/accessibility"
