#!/bin/bash

# WARNING: Please DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Pre-commit git hook to check Terraform documentation.
#
# Usage:
#   $ [options] ./check-terraform-documentation.sh
#
# Options:
#   VERBOSE=true            # Show all the executed commands, default is 'false'

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"

  terraform-docs
}

# Generate Terraform documentation.
# Arguments (provided as environment variables):
#   check_only=[do not format, run check only]
function terraform-docs() {

  make terraform-docs
  git add infrastructure/terraform/**/*.md
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
