name: PR Closed

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-merge-or-workflow-dispatch:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - name: Check if PR was merged or wor§kflow is triggered by workflow_dispatch
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "Job triggered by workflow_dispatch - running 'deploy-main'"
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "Job triggered by Merged PR - running 'deploy-main'"
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
            echo "Job not triggered by workflow_dispatch or Merged PR - Skipping 'deploy-main'"
          fi

  deploy-main:
    needs: check-merge-or-workflow-dispatch
    name: Deploy changes to main in dev AWS account
    if: needs.check-merge-or-workflow-dispatch.outputs.deploy == 'true'

    strategy:
      max-parallel: 1
      matrix:
        component: [acct, app]

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Deploy changes to main in dev AWS account
      releaseVersion: main
      targetWorkflow: "dispatch-deploy-static-notify-iam-env.yaml"
      targetEnvironment: "main"
      targetAccountGroup: "nhs-notify-iam-dev"
      targetComponent: ${{ matrix.component }}
      terraformAction: "apply"
