name: "Test stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  test-unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Repo setup"
        run: |
          npm install
      - name: "Run unit test suite"
        run: |
          npm run generate-outputs env
          make test-unit
      - name: "Save the result of fast test suite"
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests
          path: "**/.reports/unit"
          include-hidden-files: true
        if: always()
      - name: "Save the result of code coverage"
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ".reports/lcov.info"
        if: always()
  test-lint:
    name: "Linting"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Repo setup"
        run: |
          npm install
      - name: "Run linting"
        run: |
          make test-lint
      - name: "Save the linting result"
        run: |
          echo "Nothing to save"
  test-coverage:
    name: "Test coverage"
    needs: [test-unit]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - name: "Repo setup"
        run: |
          npm install
      - name: "Run test coverage check"
        run: |
          npm run generate-outputs env
          make test-coverage
  perform-static-analysis:
    name: "Perform static analysis"
    needs: [test-unit]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Full history is needed to improving relevancy of reporting
      - name: "Download coverage report for SONAR"
        uses: actions/download-artifact@v5
        with:
          name: code-coverage-report
      - name: "Perform static analysis"
        uses: ./.github/actions/perform-static-analysis
        with:
          sonar_organisation_key: "${{ vars.SONAR_ORGANISATION_KEY }}"
          sonar_project_key: "${{ vars.SONAR_PROJECT_KEY }}"
          sonar_token: "${{ secrets.SONAR_TOKEN }}"
